-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 18:29:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`клиенты` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`недвига`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`недвига` (
  `id` INT NOT NULL,
  `kontora_id` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `rooms` INT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`конторы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`конторы` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_конторы_клиенты1_idx` (`adress` ASC) VISIBLE,
  CONSTRAINT `fk_конторы_клиенты1`
    FOREIGN KEY (`adress`)
    REFERENCES `mydb`.`клиенты` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_конторы_недвига1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`недвига` (`kontora_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1_has_table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1_has_table2` (
  `table1_tdh` INT NOT NULL,
  `table2_yfyt` INT NOT NULL,
  PRIMARY KEY (`table1_tdh`, `table2_yfyt`),
  INDEX `fk_table1_has_table2_table21_idx` (`table2_yfyt` ASC) VISIBLE,
  INDEX `fk_table1_has_table2_table1_idx` (`table1_tdh` ASC) VISIBLE,
  CONSTRAINT `fk_table1_has_table2_table1`
    FOREIGN KEY (`table1_tdh`)
    REFERENCES `mydb`.`конторы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_has_table2_table21`
    FOREIGN KEY (`table2_yfyt`)
    REFERENCES `mydb`.`клиенты` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`конторы_has_клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`конторы_has_клиенты` (
  `конторы_id` INT NOT NULL,
  `клиенты_id` INT NOT NULL,
  PRIMARY KEY (`конторы_id`, `клиенты_id`),
  INDEX `fk_конторы_has_клиенты_клиенты1_idx` (`клиенты_id` ASC) VISIBLE,
  INDEX `fk_конторы_has_клиенты_конторы1_idx` (`конторы_id` ASC) VISIBLE,
  CONSTRAINT `fk_конторы_has_клиенты_конторы1`
    FOREIGN KEY (`конторы_id`)
    REFERENCES `mydb`.`конторы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_конторы_has_клиенты_клиенты1`
    FOREIGN KEY (`клиенты_id`)
    REFERENCES `mydb`.`клиенты` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
